"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type LanguageCode = "en" | "hi" | "es" | "fr";

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
];

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navigation & Sidebar
    dashboard: "Dashboard",
    employees: "Employees",
    analytics: "Analytics",
    tasks: "Tasks",
    notifications: "Notifications",
    workspace_hub: "Workspace Hub",
    profile: "Profile",
    settings: "Settings",
    help: "Help & Support",
    sign_out: "Sign Out",
    admin_portal: "Admin Portal",
    overview: "Overview",
    workspace: "Workspace",
    system_mgmt: "System & Management",
    system_admin: "System Administrator",
    emp_workspace: "Employee Workspace",
    active_status: "Active",
    expand_sidebar: "Expand sidebar",
    collapse_sidebar: "Collapse sidebar",

    // Topbar
    search_placeholder: "Search anything...",
    search_workspace: "Search workspace...",
    display_scale: "Display Size",
    language: "Language",
    text_size: "Display Scale",
    size_compact: "Compact (90%)",
    size_default: "Default (100%)",
    size_medium: "Medium (110%)",
    size_large: "Large (125%)",
    size_xlarge: "Extra Large (135%)",
    size_huge: "Maximum (150%)",
    reset_size: "Reset to 100%",
    zoom_level: "Zoom Level",
    accessibility_display: "Display & Accessibility",
    notifications_title: "Notifications",
    mark_all_read: "Mark All Read",
    view_all_notifications: "View All Notifications",
    no_notifications: "No new notifications",
    signed_in_as: "Signed in as",
    admin_role: "Administrator",
    employee_role: "Team Member",
    toggle_theme: "Toggle theme",
    switch_light: "Switch to light mode",
    switch_dark: "Switch to dark mode",
    decrease_size: "Decrease size",
    increase_size: "Increase size",
    lang_set_to: "Language set to",

    // Employees Page
    emp_directory_title: "Employee Directory",
    emp_directory_subtitle: "Review employee roster, manage roles, edit credentials, and control access permissions.",
    all_members: "All Members",
    active_staff: "Active Staff",
    blocked_staff: "Blocked / Suspended",
    export_csv: "Export CSV",
    search_emp_placeholder: "Search by name, email, employee ID, role...",
    all_depts: "All Departments",
    sort_name_asc: "Name (A-Z)",
    sort_name_desc: "Name (Z-A)",
    sort_department: "Department",
    col_employee: "EMPLOYEE",
    col_id_code: "ID CODE",
    col_department: "DEPARTMENT",
    col_role: "ROLE / TITLE",
    col_phone: "PHONE",
    col_status: "STATUS",
    col_actions: "ACTIONS",
    status_active: "ACTIVE",
    status_blocked: "BLOCKED",
    members_selected: "members selected",
    member_selected: "member selected",
    clear_selection: "Clear Selection",
    clear: "Clear",
    total_personnel: "Total Personnel:",
    quick_options: "Quick Options",
    copy_id: "Copy ID",
    copy_email: "Copy Email",
    view_performance: "View Performance",
    edit_credentials: "Edit Credentials",
    suspend_access: "Suspend Access",
    unblock_account: "Unblock Account",
    delete_account: "Delete Account",
    view_label: "View",
    edit_label: "Edit",
    block_label: "Block",
    unblock_label: "Unblock",
    delete_label: "Delete",
    cancel: "Cancel",
    block_and_logout: "Block & Logout",
    no_employees_match: "No employees match your search or filter.",
    reset_filters: "Reset Filters",

    // Tasks Page Header & Tabs
    tasks_workspace: "Tasks Workspace",
    tasks_subtitle: "Manage and assign enterprise tasks across teams and employees.",
    spaces: "Spaces",
    empsphere_workspaces: "EmpSphere Workspaces",
    tab_summary: "Summary",
    tab_list: "List",
    tab_board: "Board",
    tab_timeline: "Timeline",
    tab_reports: "Forms & Reports",
    create_task: "Create Task",
    create: "Create",
    export: "Export",
    refresh: "Refresh",
    search_work: "Search work (title, key, dept)...",
    only_my_tasks: "Only my tasks",
    filter: "Filter",
    group_by: "Group Tasks By",
    group_none: "None (Flat List)",
    group_status: "Status",
    group_priority: "Priority",
    group_department: "Department",
    sort_by: "Sort",
    sort_newest: "Newest First",
    sort_oldest: "Oldest First",
    sort_due_date: "Due Date (Soonest)",
    sort_priority: "Priority (High to Low)",
    showing: "Showing",
    of: "of",
    tasks_label: "tasks",
    show_per_page: "Show:",
    per_page: "per page",

    // Table Column Headers
    col_key: "KEY",
    col_summary: "SUMMARY",
    col_assignee: "ASSIGNEE",
    col_reporter: "REPORTER",
    col_priority: "PRIORITY",
    col_resolution: "RESOLUTION",
    col_assign_date: "ASSIGN DATE",
    col_end_date: "END DATE",

    // Statuses & Priorities
    status_todo: "TO DO",
    status_in_progress: "IN PROGRESS",
    status_review: "IN REVIEW",
    status_done: "DONE",
    status_overdue: "Overdue",
    priority_urgent: "Urgent",
    priority_high: "High",
    priority_medium: "Medium",
    priority_low: "Low",
    resolved: "Resolved",
    unresolved: "Unresolved",
    unassigned: "Unassigned",
    all_statuses: "All Statuses",
    all_priorities: "All Priorities",
    all_departments: "All Departments",
    due_today: "Due Today",
    due_this_week: "Due This Week",
    any_time: "Any Time",

    // Row Actions
    delete_task: "Delete Task",
    view_details: "View Details",
    edit_task: "Edit Task",
    copy_key: "Copy Key",
    copy_link: "Copy Link",
    duplicate_task: "Duplicate Task",
    quick_actions: "Quick Actions",
    previous: "Previous",
    next: "Next",
    page: "Page",

    // Analytics Page
    analytics_title: "Performance & Analytics",
    analytics_admin_sub: "Comprehensive enterprise performance, headcount growth, and task analytics.",
    analytics_user_sub: "Detailed breakdown of your task velocity, delivery stats, and productivity trends.",
    total_ent_users: "Total Enterprise Users",
    my_assigned_tasks: "My Assigned Tasks",
    verified_members: "Verified Team Members",
    total_workload_items: "Total Workload Items",
    prod_velocity: "Productivity Velocity",
    task_comp_rate: "Task Completion Rate",
    completed_milestones: "Delivered Milestones",
    completed_tasks_title: "Completed Tasks",
    in_prog_review: "In Progress & Review",
    active_pipeline: "Current Active Pipeline",
    org_growth_velocity: "Organization Growth & Task Velocity",
    monthly_delivery_velocity: "Monthly Task Delivery Velocity",
    task_status_breakdown: "Task Status Breakdown",
    weekly_task_cadence: "Weekly Task Cadence (Mon – Sun)",
    workload_priority: "Workload by Priority Level",
    dept_distribution_title: "Department Distribution",
    workforce_demographics: "Workforce Age Demographics",

    // Notifications Page
    notif_hub_title: "Notification & Activity Hub",
    notif_hub_sub: "Real-time employee activity stream, task updates, and workspace alerts.",
    activity_center: "Activity Center",
    all_caught_up: "All Caught Up",
    unread_and_new: "Unread & New",
    all_activity_logs: "All Activity Logs",
    workspace_messages: "Workspace Messages",
    search_notif_placeholder: "Search notifications, tasks, or members...",
    no_notifs_found: "No notifications found",

    // Dashboard & Widgets
    good_day: "Good Day",
    admin_overview: "Admin Overview",
    workspace_overview: "Workspace Overview",
    view_my_tasks: "View My Tasks",
    manage_tasks: "Manage Tasks",
    total_tasks: "TOTAL TASKS",
    pending: "PENDING",
    in_progress: "IN PROGRESS",
    completed: "COMPLETED",
    overdue: "OVERDUE",
    completion_rate: "COMPLETION RATE",
    task_distribution: "Task Distribution",
    realtime_breakdown: "Real-time status breakdown",
    weekly_activity: "Weekly Activity",
    weekly_subtitle: "Created vs Completed this week",
    live_badge: "Live",
    created_label: "Created",
    completed_label: "Completed",
    dept_workload: "Department Workload & Delivery Matrix",
    dept_subtitle: "Live task execution velocity and completion breakdown across teams",
    team_directory: "Team Directory →",
    total_label: "Total",
    active_label: "Active",
    pending_backlog: "pending backlog",
    view_tasks_arrow: "View Tasks →",
    dept_operations: "Operations",
    dept_engineering: "Engineering",
    dept_sales: "Sales & Business Dev",
    dept_design: "Design",
    dept_hr: "Human Resources",
    dept_leadership: "Executive Leadership",
    recent_activity: "Recent Activity",
    recent_subtitle: "Real-time updates and task state transitions",
    view_all_tasks: "View All Tasks",
    no_recent_activities: "No recent activities recorded",
    workspace_calendar: "Workspace Calendar",
    interactive: "Interactive",
    day_schedule: "Day Schedule & History",
    no_tasks_date: "No tasks scheduled or created on this date.",
    high_priority_attention: "High Priority Attention",
    no_due_date: "No due date",
    no_urgent_tasks: "No urgent tasks requiring attention.",
    days_mo: "Mo",
    days_tu: "Tu",
    days_we: "We",
    days_th: "Th",
    days_fr: "Fr",
    days_sa: "Sa",
    days_su: "Su",
    task_singular: "task",
    tasks_plural: "tasks",
    quick_shortcuts: "Quick Shortcuts & System Status",
    system_operational: "All Systems Operational",
    system_uptime: "99.98% Uptime SLA",
    sprint_goals: "Sprint Velocity & Goals",
    monthly_milestone: "Monthly Milestone Target",
    top_contributors: "Top Team Contributors",
    velocity_on_track: "On Track",
    tasks_completed_count: "tasks completed",
    export_report: "Export Audit Report",
    invite_member: "Invite Team Member",

    // Auth Pages (Login, Register, Forgot, Reset, Admin)
    auth_welcome_back: "Welcome back",
    auth_login_subtitle: "Log in to your workspace and pick up where you left off.",
    auth_work_email: "Work Email",
    auth_password: "Password",
    auth_remember_me: "Remember me",
    auth_forgot_password: "Forgot password?",
    auth_login_btn: "Login",
    auth_logging_in: "Logging in...",
    auth_new_to_empsphere: "New to EmpSphere?",
    auth_create_account: "Create an account",
    auth_create_title: "Create your account",
    auth_create_subtitle: "Get started with your team's task management workspace.",
    auth_required_hint: "Fields marked with an asterisk (*) are required.",
    auth_first_name: "First Name",
    auth_last_name: "Last Name",
    auth_phone_number: "Phone Number",
    auth_department: "Department",
    auth_select_department: "Select department",
    auth_role: "Your Role",
    auth_select_role: "Select your role",
    auth_confirm_password: "Confirm Password",
    auth_emp_id: "Employee ID",
    auth_emp_id_hint: "Assigned automatically. Can be edited by admin later.",
    auth_dob: "Date of Birth",
    auth_dob_hint: "Must be at least 18 years old",
    auth_agree_terms: "I agree to the",
    auth_terms: "Terms of Service",
    auth_and: "&",
    auth_privacy: "Privacy Policy",
    auth_create_btn: "Create Account",
    auth_creating_account: "Creating Account...",
    auth_clear_draft: "Clear Form Draft",
    auth_already_have_account: "Already have an account?",
    auth_sign_in_link: "Log in",
    auth_forgot_title: "Forgot password?",
    auth_forgot_subtitle: "Enter the email linked to your account and we'll send you a reset link.",
    auth_send_reset_btn: "Send reset link",
    auth_sending_link: "Sending link...",
    auth_back_to_sign_in: "Back to sign in",
    auth_reset_title: "Set new password",
    auth_reset_subtitle: "Choose a strong password with letters, numbers, and symbols.",
    auth_reset_btn: "Reset password",
    auth_resetting_password: "Resetting password...",
    auth_admin_portal: "Admin Portal",
    auth_admin_title: "Admin Portal",
    auth_admin_subtitle: "Sign in with your administrator credentials",
    auth_admin_email: "Admin Email",
    auth_enter_portal: "Enter Portal",
    auth_employee_login: "Employee Login",
    auth_sec_feature1: "Enterprise-grade security",
    auth_sec_feature2: "Seamless team collaboration",
    auth_sec_feature3: "Lightning fast performance",
    auth_hero_heading: "Manage tasks with",
    auth_hero_highlight: "absolute clarity.",
    auth_hero_sub: "Join thousands of modern teams who use EmpSphere to align their organization, ship faster, and hit their goals.",

    // Home Page
    home_nav_features: "Features",
    home_nav_security: "Security",
    home_nav_analytics: "Analytics",
    home_nav_signin: "Sign In",
    home_hero_badge: "Enterprise-Grade Workforce Management Platform",
    home_hero_title1: "The OS for your",
    home_hero_title2: "modern workforce",
    home_hero_desc: "EmpSphere unifies task management, team analytics, payroll visibility, and role-based access into one beautifully designed enterprise workspace.",
    home_hero_cta: "Sign In to Workspace",
    home_stat_uptime: "Uptime SLA",
    home_stat_users: "Active Users",
    home_stat_tasks: "Tasks Managed",
    home_stat_countries: "Countries",
    home_portals_badge: "Access Portals",
    home_portals_title: "Choose your workspace",
    home_portals_desc: "Two dedicated portals. One unified platform. Secure, role-aware access for every team member.",
    home_emp_portal_badge: "Employee Portal",
    home_emp_portal_title: "Employee Sign In",
    home_emp_portal_desc: "Access your tasks, view payslips, manage your profile, track deliverables, and collaborate with your team from one dashboard.",
    home_emp_feat_1: "Personal task dashboard",
    home_emp_feat_2: "Payslip & salary overview",
    home_emp_feat_3: "Team collaboration hub",
    home_emp_feat_4: "Profile & document management",
    home_emp_btn: "Sign in as Employee",
    home_emp_new_here: "New here?",
    home_emp_create_acc: "Create account",
    home_admin_portal_badge: "Restricted Access",
    home_admin_portal_title: "Admin Portal",
    home_admin_portal_desc: "Privileged access for Super Admins, System Admins, and Administrators to manage the entire organization.",
    home_admin_feat_1: "Super Admin — Full platform control",
    home_admin_feat_2: "System Admin — Security & audit access",
    home_admin_feat_3: "Admin — User & task management",
    home_admin_feat_4: "Audit logs, analytics & reporting",
    home_admin_btn: "Sign In to Workspace",
    home_admin_subtext: "Unified enterprise login for all workspace roles",
    home_analytics_badge: "Workforce Intelligence & Insights",
    home_analytics_title: "Real-time analytics for modern leaders",
    home_analytics_desc: "Gain deep visibility into team velocity, task completion efficiency, attendance trends, and organizational productivity.",
    home_analytics_stat1_val: "94.2%",
    home_analytics_stat1_lbl: "Task Completion Velocity",
    home_analytics_stat1_sub: "+8.4% faster vs last month",
    home_analytics_stat2_val: "1.8 hrs",
    home_analytics_stat2_lbl: "Average Resolution Time",
    home_analytics_stat2_sub: "32% faster delivery time",
    home_analytics_stat3_val: "98.6%",
    home_analytics_stat3_lbl: "Workforce Active Rate",
    home_analytics_stat3_sub: "High engagement index",
    home_analytics_stat4_val: "99.4%",
    home_analytics_stat4_lbl: "SLA Adherence Rate",
    home_analytics_stat4_sub: "Zero compliance violations",
    home_analytics_card_title: "Live Productivity Matrix",
    home_analytics_card_sub: "Real-time organizational performance across departments",
    home_dept_eng: "Engineering",
    home_dept_prod: "Product Design",
    home_dept_ops: "Operations",
    home_dept_hr: "People & HR",
    home_analytics_live_feed: "Live Performance Pulse",
    home_analytics_pulse1: "Sprint 14 velocity completed ahead of schedule",
    home_analytics_pulse2: "99.8% on-time milestone delivery across active tasks",
    home_analytics_pulse3: "Zero security flags detected in monthly automated audit",
    home_features_badge: "Platform Features",
    home_features_title: "Everything your team needs",
    home_features_desc: "Built for scale, designed for clarity. EmpSphere brings every HR and productivity tool under one roof.",
    home_feat1_title: "Enterprise Security",
    home_feat1_desc: "Military-grade JWT auth, RBAC, OTP verification, and rate limiting out of the box.",
    home_feat2_title: "Real-Time Analytics",
    home_feat2_desc: "6-month growth charts, productivity scores, and live workforce metrics for leadership.",
    home_feat3_title: "Team Management",
    home_feat3_desc: "Role-based portals for Super Admin, System Admin, Admin, Manager, and Employees.",
    home_feat4_title: "Lightning Performance",
    home_feat4_desc: "Optimistic UI updates, instant token refresh, and background sync for zero-latency UX.",
    home_feat5_title: "Full Task Lifecycle",
    home_feat5_desc: "Create, assign, track, review, complete and archive tasks with full audit trails.",
    home_feat6_title: "Compliance Ready",
    home_feat6_desc: "Built-in audit logs, PAN/Aadhar/UAN fields, soft-delete, and data export for compliance.",
    home_testi_badge: "Trusted by Teams",
    home_testi_title: "Loved by thousands",
    home_cta_badge: "Get Started Today — Free",
    home_cta_title1: "Ready to transform",
    home_cta_title2: "your workforce?",
    home_cta_desc: "Join 50,000+ employees and teams who run on EmpSphere every day.",
    home_cta_create: "Create Free Account",
    home_cta_signin: "Sign In to Workspace",
    home_footer_login: "Login",
    home_footer_register: "Register",
    home_footer_forgot: "Forgot Password",
    home_footer_rights: "© 2026 EmpSphere Inc. All rights reserved.",
  },
  hi: {
    // Navigation & Sidebar
    dashboard: "डैशबोर्ड",
    employees: "कर्मचारी (Employees)",
    analytics: "एनालिटिक्स (Analytics)",
    tasks: "कार्य (Tasks)",
    notifications: "सूचनाएं (Notifications)",
    workspace_hub: "वर्कस्पेस हब",
    profile: "प्रोफ़ाइल (Profile)",
    settings: "सेटिंग्स (Settings)",
    help: "सहायता व सहयोग",
    sign_out: "साइन आउट",
    admin_portal: "व्यवस्थापक पोर्टल (Admin Portal)",
    overview: "अवलोकन",
    workspace: "कार्यक्षेत्र",
    system_mgmt: "सिस्टम और प्रबंधन",
    system_admin: "सिस्टम व्यवस्थापक",
    emp_workspace: "कर्मचारी कार्यक्षेत्र",
    active_status: "सक्रिय",
    expand_sidebar: "साइडबार खोलें",
    collapse_sidebar: "साइडबार समेटें",

    // Topbar
    search_placeholder: "खोजें...",
    search_workspace: "वर्कस्पेस खोजें...",
    display_scale: "डिस्प्ले आकार (Display Scale)",
    language: "भाषा (Language)",
    text_size: "आकार (Scale)",
    size_compact: "छोटा (90%)",
    size_default: "सामान्य (100%)",
    size_medium: "मध्यम (110%)",
    size_large: "बड़ा (125%)",
    size_xlarge: "अतिरिक्त बड़ा (135%)",
    size_huge: "अधिकतम (150%)",
    reset_size: "100% पर रीसेट करें",
    zoom_level: "ज़ूम स्तर",
    accessibility_display: "डिस्प्ले और सुगमता",
    notifications_title: "सूचनाएं",
    mark_all_read: "सभी पढ़ें चिह्नित करें",
    view_all_notifications: "सभी सूचनाएं देखें",
    no_notifications: "कोई नई सूचना नहीं",
    signed_in_as: "लॉग इन उपयोगकर्ता:",
    admin_role: "व्यवस्थापक (Admin)",
    employee_role: "टीम सदस्य",
    toggle_theme: "थीम बदलें",
    switch_light: "लाइट मोड",
    switch_dark: "डार्क मोड",
    decrease_size: "आकार छोटा करें",
    increase_size: "आकार बड़ा करें",
    lang_set_to: "भाषा बदली गई:",

    // Employees Page
    emp_directory_title: "कर्मचारी डायरेक्टरी (Employee Directory)",
    emp_directory_subtitle: "कर्मचारी रोस्टर देखें, भूमिकाएं प्रबंधित करें और क्रेडेंशियल संपादित करें।",
    all_members: "सभी सदस्य (All)",
    active_staff: "सक्रिय कर्मचारी (Active)",
    blocked_staff: "अवरुद्ध / निलंबित (Blocked)",
    export_csv: "CSV निर्यात करें",
    search_emp_placeholder: "नाम, ईमेल, कर्मचारी आईडी या पद से खोजें...",
    all_depts: "सभी विभाग (All Departments)",
    sort_name_asc: "नाम (A-Z)",
    sort_name_desc: "नाम (Z-A)",
    sort_department: "विभाग",
    col_employee: "कर्मचारी (EMPLOYEE)",
    col_id_code: "आईडी कोड (ID CODE)",
    col_department: "विभाग (DEPARTMENT)",
    col_role: "पद / भूमिका (ROLE)",
    col_phone: "फ़ोन (PHONE)",
    col_status: "स्थिति (STATUS)",
    col_actions: "क्रियाएं (ACTIONS)",
    status_active: "सक्रिय (ACTIVE)",
    status_blocked: "अवरुद्ध (BLOCKED)",
    members_selected: "सदस्य चुने गए",
    member_selected: "सदस्य चुना गया",
    clear_selection: "चयन साफ़ करें",
    clear: "साफ़ करें",
    total_personnel: "कुल कर्मचारी:",
    quick_options: "त्वरित विकल्प",
    copy_id: "आईडी कॉपी करें",
    copy_email: "ईमेल कॉपी करें",
    view_performance: "प्रदर्शन देखें",
    edit_credentials: "क्रेडेंशियल संपादित करें",
    suspend_access: "पहुंच निलंबित करें",
    unblock_account: "अकाउंट अनब्लॉक करें",
    delete_account: "खाता हटाएं",
    view_label: "देखें",
    edit_label: "संपादित करें",
    block_label: "ब्लॉक",
    unblock_label: "अनब्लॉक",
    delete_label: "हटाएं",
    cancel: "रद्द करें",
    block_and_logout: "ब्लॉक और लॉगआउट करें",
    no_employees_match: "आपकी खोज या फ़िल्टर से कोई कर्मचारी मेल नहीं खाता।",
    reset_filters: "फ़िल्टर रीसेट करें",

    // Tasks Page Header & Tabs
    tasks_workspace: "कार्यक्षेत्र (Tasks Workspace)",
    tasks_subtitle: "टीम और कर्मचारियों के बीच एंटरप्राइज़ कार्यों का प्रबंधन और आवंटन करें।",
    spaces: "स्पेस",
    empsphere_workspaces: "एम्पस्फ़ीयर वर्कस्पेस",
    tab_summary: "सारांश (Summary)",
    tab_list: "सूची (List)",
    tab_board: "बोर्ड (Board)",
    tab_timeline: "समयरेखा (Timeline)",
    tab_reports: "फ़ॉर्म और रिपोर्ट",
    create_task: "नया कार्य बनाएं",
    create: "+ बनाएं",
    export: "निर्यात (Export)",
    refresh: "रिफ्रेश",
    search_work: "कार्य खोजें (शीर्षक, कुंजी, विभाग)...",
    only_my_tasks: "केवल मेरे कार्य",
    filter: "फ़िल्टर",
    group_by: "समूहीकृत करें",
    group_none: "कोई नहीं (सपाट सूची)",
    group_status: "स्थिति अनुसार",
    group_priority: "प्राथमिकता अनुसार",
    group_department: "विभाग अनुसार",
    sort_by: "क्रमबद्ध करें",
    sort_newest: "नवीनतम पहले",
    sort_oldest: "पुरातन पहले",
    sort_due_date: "नियत तिथि (शीघ्र)",
    sort_priority: "प्राथमिकता (उच्च से निम्न)",
    showing: "दिखाया जा रहा है",
    of: "में से",
    tasks_label: "कार्य",
    show_per_page: "प्रति पृष्ठ:",
    per_page: "कार्य प्रति पृष्ठ",

    // Table Column Headers
    col_key: "कुंजी (KEY)",
    col_summary: "कार्य सारांश (SUMMARY)",
    col_assignee: "सौंपा गया (ASSIGNEE)",
    col_reporter: "रिपोर्टर (REPORTER)",
    col_priority: "प्राथमिकता (PRIORITY)",
    col_resolution: "समाधान (RESOLUTION)",
    col_assign_date: "आवंटन तिथि (ASSIGN DATE)",
    col_end_date: "समाप्ति तिथि (END DATE)",

    // Statuses & Priorities
    status_todo: "करना है (TO DO)",
    status_in_progress: "प्रगति पर (IN PROGRESS)",
    status_review: "समीक्षाधीन (IN REVIEW)",
    status_done: "पूर्ण (DONE)",
    status_overdue: "अतिदेय (Overdue)",
    priority_urgent: "अति आवश्यक (Urgent)",
    priority_high: "उच्च (High)",
    priority_medium: "मध्यम (Medium)",
    priority_low: "निम्न (Low)",
    resolved: "समाधान हुआ",
    unresolved: "असमाधानित",
    unassigned: "अनसुलझा / कोई नहीं",
    all_statuses: "सभी स्थितियां",
    all_priorities: "सभी प्राथमिकताएं",
    all_departments: "सभी विभाग",
    due_today: "आज देय",
    due_this_week: "इस सप्ताह देय",
    any_time: "किसी भी समय",

    // Row Actions
    delete_task: "कार्य हटाएं",
    view_details: "विवरण देखें",
    edit_task: "कार्य संपादित करें",
    copy_key: "कुंजी कॉपी करें",
    copy_link: "लिंक कॉपी करें",
    duplicate_task: "प्रतिलिपि बनाएं",
    quick_actions: "त्वरित क्रियाएं",
    previous: "पिछला",
    next: "अगला",
    page: "पृष्ठ",

    // Analytics Page
    analytics_title: "प्रदर्शन और एनालिटिक्स (Analytics)",
    analytics_admin_sub: "उद्यम प्रदर्शन, कार्यबल वृद्धि और कार्य विश्लेषण।",
    analytics_user_sub: "आपकी कार्य गति, वितरण आंकड़े और उत्पादकता रुझान।",
    total_ent_users: "कुल उद्यम उपयोगकर्ता",
    my_assigned_tasks: "मेरे सौंपे गए कार्य",
    verified_members: "सत्यापित टीम सदस्य",
    total_workload_items: "कुल कार्यभार आइटम",
    prod_velocity: "उत्पादकता गति (Velocity)",
    task_comp_rate: "कार्य पूर्णता दर",
    completed_milestones: "वितरित मील के पत्थर",
    completed_tasks_title: "पूर्ण किए गए कार्य",
    in_prog_review: "प्रगति और समीक्षा में",
    active_pipeline: "वर्तमान सक्रिय पाइपलाइन",
    org_growth_velocity: "संगठन विकास और कार्य गति",
    monthly_delivery_velocity: "मासिक कार्य वितरण गति",
    task_status_breakdown: "कार्य स्थिति विवरण",
    weekly_task_cadence: "साप्ताहिक कार्य चक्र (सोम – रवि)",
    workload_priority: "प्राथमिकता स्तर अनुसार कार्यभार",
    dept_distribution_title: "विभाग वितरण",
    workforce_demographics: "कार्यबल आयु जनसांख्यिकी",

    // Notifications Page
    notif_hub_title: "सूचना एवं गतिविधि केंद्र (Notifications)",
    notif_hub_sub: "रीयल-टाइम कर्मचारी गतिविधि स्ट्रीम, कार्य अपडेट और वर्कस्पेस अलर्ट।",
    activity_center: "गतिविधि केंद्र",
    all_caught_up: "सब कुछ देखा जा चुका है",
    unread_and_new: "अपठित एवं नई",
    all_activity_logs: "सभी गतिविधि लॉग",
    workspace_messages: "कार्यक्षेत्र संदेश",
    search_notif_placeholder: "सूचनाएं, कार्य या सदस्य खोजें...",
    no_notifs_found: "कोई सूचना नहीं मिली",

    // Dashboard
    good_day: "नमस्ते / शुभ दिन",
    admin_overview: "व्यवस्थापक अवलोकन",
    workspace_overview: "कार्यक्षेत्र अवलोकन",
    view_my_tasks: "मेरे कार्य देखें",
    manage_tasks: "कार्यों का प्रबंधन करें",
    total_tasks: "कुल कार्य",
    pending: "लंबित कार्य",
    in_progress: "प्रगति पर कार्य",
    completed: "पूर्ण कार्य",
    overdue: "अतिदेय कार्य",
    completion_rate: "पूर्णता दर",
    task_distribution: "कार्य स्थिति वितरण",
    realtime_breakdown: "रीयल-टाइम स्थिति विवरण",
    weekly_activity: "साप्ताहिक गतिविधि",
    weekly_subtitle: "इस सप्ताह बनाए गए बनाम पूर्ण कार्य",
    live_badge: "लाइव",
    created_label: "बनाया गया",
    completed_label: "पूर्ण किया गया",
    dept_workload: "विभाग कार्यभार एवं वितरण मैट्रिक्स",
    dept_subtitle: "टीमों में कार्य निष्पादन गति और पूर्णता विवरण",
    team_directory: "टीम डायरेक्टरी →",
    total_label: "कुल",
    active_label: "सक्रिय",
    pending_backlog: "लंबित बैकलॉग",
    view_tasks_arrow: "कार्य देखें →",
    dept_operations: "ऑपरेशंस (संचालन)",
    dept_engineering: "इंजीनियरिंग",
    dept_sales: "बिक्री एवं व्यापार विकास",
    dept_design: "डिजाइन",
    dept_hr: "मानव संसाधन (HR)",
    dept_leadership: "कार्यकारी नेतृत्व",
    recent_activity: "हाल की गतिविधि",
    recent_subtitle: "रीयल-टाइम अपडेट एवं कार्य स्थिति परिवर्तन",
    view_all_tasks: "सभी कार्य देखें",
    no_recent_activities: "कोई हाल की गतिविधि दर्ज नहीं है",
    workspace_calendar: "कार्यक्षेत्र कैलेंडर",
    interactive: "इंटरैक्टिव",
    day_schedule: "दिन की समय सारणी एवं इतिहास",
    no_tasks_date: "इस तिथि पर कोई कार्य निर्धारित या बनाया नहीं गया है।",
    high_priority_attention: "उच्च प्राथमिकता ध्यान",
    no_due_date: "कोई नियत तिथि नहीं",
    no_urgent_tasks: "ध्यान देने की आवश्यकता वाले कोई अति आवश्यक कार्य नहीं।",
    days_mo: "सोम",
    days_tu: "मं",
    days_we: "बुध",
    days_th: "गुरु",
    days_fr: "शुक्र",
    days_sa: "शनि",
    days_su: "रवि",
    task_singular: "कार्य",
    tasks_plural: "कार्य",
    quick_shortcuts: "त्वरित शॉर्टकट एवं सिस्टम स्थिति",
    system_operational: "सभी सिस्टम सुचारू रूप से कार्यरत",
    system_uptime: "99.98% अपटाइम SLA",
    sprint_goals: "स्प्रिंट गति एवं लक्ष्य",
    monthly_milestone: "मासिक मील का पत्थर लक्ष्य",
    top_contributors: "शीर्ष टीम योगदानकर्ता",
    velocity_on_track: "समय पर (On Track)",
    tasks_completed_count: "कार्य पूर्ण किए",
    export_report: "ऑडिट रिपोर्ट निर्यात करें",
    invite_member: "टीम सदस्य को आमंत्रित करें",

    // Auth Pages (Login, Register, Forgot, Reset, Admin)
    auth_welcome_back: "वापसी पर स्वागत है",
    auth_login_subtitle: "अपने कार्यक्षेत्र में लॉग इन करें और काम शुरू करें।",
    auth_work_email: "कार्य ईमेल (Work Email)",
    auth_password: "पासवर्ड (Password)",
    auth_remember_me: "मुझे याद रखें",
    auth_forgot_password: "पासवर्ड भूल गए?",
    auth_login_btn: "लॉग इन करें",
    auth_logging_in: "लॉग इन हो रहा है...",
    auth_new_to_empsphere: "EmpSphere पर नए हैं?",
    auth_create_account: "खाता बनाएं",
    auth_create_title: "अपना खाता बनाएं",
    auth_create_subtitle: "अपनी टीम के कार्य प्रबंधन वर्कस्पेस की शुरुआत करें।",
    auth_required_hint: "तारांकन चिह्न (*) वाले फ़ील्ड आवश्यक हैं।",
    auth_first_name: "पहला नाम (First Name)",
    auth_last_name: "अंतिम नाम (Last Name)",
    auth_phone_number: "फ़ोन नंबर (Phone Number)",
    auth_department: "विभाग (Department)",
    auth_select_department: "विभाग चुनें",
    auth_role: "आपकी भूमिका (Role)",
    auth_select_role: "भूमिका चुनें",
    auth_confirm_password: "पासवर्ड की पुष्टि करें",
    auth_emp_id: "कर्मचारी आईडी (Employee ID)",
    auth_emp_id_hint: "स्वचालित रूप से आवंटित। बाद में व्यवस्थापक द्वारा संपादित किया जा सकता है।",
    auth_dob: "जन्म तिथि (Date of Birth)",
    auth_dob_hint: "कम से कम 18 वर्ष का होना आवश्यक है",
    auth_agree_terms: "मैं सहमत हूँ",
    auth_terms: "सेवा की शर्तें (Terms)",
    auth_and: "एवं",
    auth_privacy: "गोपनीयता नीति (Privacy)",
    auth_create_btn: "खाता बनाएं",
    auth_creating_account: "खाता बनाया जा रहा है...",
    auth_clear_draft: "फ़ॉर्म ड्राफ़्ट साफ़ करें",
    auth_already_have_account: "क्या आपके पास पहले से खाता है?",
    auth_sign_in_link: "लॉग इन करें",
    auth_forgot_title: "पासवर्ड भूल गए?",
    auth_forgot_subtitle: "अपने खाते से जुड़ा ईमेल दर्ज करें और हम आपको एक रीसेट लिंक भेजेंगे।",
    auth_send_reset_btn: "रीसेट लिंक भेजें",
    auth_sending_link: "लिंक भेजा जा रहा है...",
    auth_back_to_sign_in: "साइन इन पर वापस जाएं",
    auth_reset_title: "नया पासवर्ड सेट करें",
    auth_reset_subtitle: "अक्षरों, संख्याओं और प्रतीकों के साथ एक मजबूत पासवर्ड चुनें।",
    auth_reset_btn: "पासवर्ड रीसेट करें",
    auth_resetting_password: "पासवर्ड अपडेट हो रहा है...",
    auth_admin_portal: "व्यवस्थापक पोर्टल (Admin Portal)",
    auth_admin_title: "एडमिन पोर्टल",
    auth_admin_subtitle: "अपने व्यवस्थापक क्रेडेंशियल से साइन इन करें",
    auth_admin_email: "एडमिन ईमेल",
    auth_enter_portal: "पोर्टल में प्रवेश करें",
    auth_employee_login: "कर्मचारी लॉगिन (Employee Login)",
    auth_sec_feature1: "एंटरप्राइज़-ग्रेड सुरक्षा",
    auth_sec_feature2: "सहज टीम सहयोग",
    auth_sec_feature3: "अत्यंत तीव्र प्रदर्शन",
    auth_hero_heading: "कार्यों का प्रबंधन करें",
    auth_hero_highlight: "पूर्ण स्पष्टता के साथ।",
    auth_hero_sub: "हजारों आधुनिक टीमों से जुड़ें जो अपने संगठन को संरेखित करने के लिए EmpSphere का उपयोग करती हैं।",

    // Home Page (Hindi)
    home_nav_features: "विशेषताएं (Features)",
    home_nav_security: "सुरक्षा (Security)",
    home_nav_analytics: "एनालिटिक्स (Analytics)",
    home_nav_signin: "साइन इन",
    home_hero_badge: "एंटरप्राइज-ग्रेड वर्कफ़ोर्स मैनेजमेंट प्लेटफ़ॉर्म",
    home_hero_title1: "आपके आधुनिक कार्यबल के लिए",
    home_hero_title2: "शक्तिशाली OS",
    home_hero_desc: "EmpSphere कार्य प्रबंधन, टीम एनालिटिक्स, पेरोल दृश्यता और भूमिका-आधारित पहुंच को एक सुंदर एंटरप्राइज वर्कस्पेस में एकीकृत करता है।",
    home_hero_cta: "वर्कस्पेस में साइन इन करें",
    home_stat_uptime: "अपटाइम SLA",
    home_stat_users: "सक्रिय उपयोगकर्ता",
    home_stat_tasks: "प्रबंधित कार्य",
    home_stat_countries: "वैश्विक देश",
    home_portals_badge: "एक्सेस पोर्टल",
    home_portals_title: "अपना वर्कस्पेस चुनें",
    home_portals_desc: "दो समर्पित पोर्टल। एक एकीकृत प्लेटफ़ॉर्म। प्रत्येक टीम सदस्य के लिए सुरक्षित और भूमिका-जागरूक पहुंच।",
    home_emp_portal_badge: "कर्मचारी पोर्टल",
    home_emp_portal_title: "कर्मचारी साइन इन",
    home_emp_portal_desc: "अपने कार्यों तक पहुंचें, सैलरी स्लिप देखें, प्रोफ़ाइल प्रबंधित करें और एक ही डैशबोर्ड से अपनी टीम के साथ सहयोग करें।",
    home_emp_feat_1: "व्यक्तिगत कार्य डैशबोर्ड",
    home_emp_feat_2: "वेतन व पेरोल अवलोकन",
    home_emp_feat_3: "टीम सहयोग हब",
    home_emp_feat_4: "प्रोफ़ाइल व दस्तावेज़ प्रबंधन",
    home_emp_btn: "कर्मचारी के रूप में साइन इन करें",
    home_emp_new_here: "नए उपयोगकर्ता हैं?",
    home_emp_create_acc: "खाता बनाएं",
    home_admin_portal_badge: "प्रतिबंधित पहुंच",
    home_admin_portal_title: "व्यवस्थापक (Admin) पोर्टल",
    home_admin_portal_desc: "पूरे संगठन को प्रबंधित करने के लिए सुपर एडमिन और सिस्टम एडमिन के लिए विशेषाधिकार प्राप्त पहुंच।",
    home_admin_feat_1: "सुपर एडमिन — पूर्ण प्लेटफ़ॉर्म नियंत्रण",
    home_admin_feat_2: "सिस्टम एडमिन — सुरक्षा व ऑडिट नियंत्रण",
    home_admin_feat_3: "एडमिन — कर्मचारी व कार्य प्रबंधन",
    home_admin_feat_4: "ऑडिट लॉग्स, एनालिटिक्स व विस्तृत रिपोर्टिंग",
    home_admin_btn: "वर्कस्पेस में साइन इन करें",
    home_admin_subtext: "सभी वर्कस्पेस भूमिकाओं के लिए एकीकृत लॉगिन",
    home_analytics_badge: "वर्कफ़ोर्स इंटेलिजेंस और अंतर्दृष्टि",
    home_analytics_title: "आधुनिक लीडर्स के लिए रियल-टाइम एनालिटिक्स",
    home_analytics_desc: "टीम की कार्य गति, कार्य पूर्णता दक्षता, उपस्थिति रुझान और समग्र उत्पादकता पर गहरी दृश्यता प्राप्त करें।",
    home_analytics_stat1_val: "94.2%",
    home_analytics_stat1_lbl: "कार्य पूर्णता दर",
    home_analytics_stat1_sub: "पिछले माह की तुलना में +8.4% तीव्र",
    home_analytics_stat2_val: "1.8 घंटे",
    home_analytics_stat2_lbl: "औसत समाधान समय",
    home_analytics_stat2_sub: "32% तीव्र डिलीवरी समय",
    home_analytics_stat3_val: "98.6%",
    home_analytics_stat3_lbl: "कार्यबल सक्रियता दर",
    home_analytics_stat3_sub: "उच्चतम भागीदारी सूचकांक",
    home_analytics_stat4_val: "99.4%",
    home_analytics_stat4_lbl: "SLA अनुपालन दर",
    home_analytics_stat4_sub: "शून्य अनुपालन उल्लंघन",
    home_analytics_card_title: "लाइव उत्पादकता मैट्रिक्स",
    home_analytics_card_sub: "विभागों में वास्तविक समय का संगठनात्मक प्रदर्शन",
    home_dept_eng: "इंजीनियरिंग",
    home_dept_prod: "उत्पाद डिज़ाइन",
    home_dept_ops: "संचालन (Operations)",
    home_dept_hr: "मानव संसाधन (HR)",
    home_analytics_live_feed: "लाइव प्रदर्शन पल्स",
    home_analytics_pulse1: "स्प्रिंट 14 निर्धारित समय से पहले पूर्ण हुआ",
    home_analytics_pulse2: "सक्रिय कार्यों में 99.8% समय पर डिलीवरी",
    home_analytics_pulse3: "मासिक स्वचालित ऑडिट में शून्य सुरक्षा जोखिम मिले",
    home_features_badge: "प्लेटफ़ॉर्म विशेषताएं",
    home_features_title: "आपकी टीम की हर आवश्यकता",
    home_features_desc: "पैमाने के लिए निर्मित, स्पष्टता के लिए डिज़ाइन किया गया। EmpSphere सभी HR और उत्पादकता टूल्स को एक मंच पर लाता है।",
    home_feat1_title: "एंटरप्राइज़ सुरक्षा",
    home_feat1_desc: "सुरक्षित JWT ऑथ, RBAC, OTP सत्यापन और स्वचालित दर सीमितीकरण।",
    home_feat2_title: "रियल-टाइम एनालिटिक्स",
    home_feat2_desc: "6-महीने के विकास चार्ट, उत्पादकता स्कोर और लाइव मेट्रिक्स।",
    home_feat3_title: "टीम प्रबंधन",
    home_feat3_desc: "सुपर एडमिन, सिस्टम एडमिन, मैनेजर और कर्मचारियों के लिए अलग पोर्टल।",
    home_feat4_title: "अत्यंत तीव्र प्रदर्शन",
    home_feat4_desc: "शून्य विलंबता और तत्काल टोकन रिफ्रेश के साथ हाई-स्पीड अनुभव।",
    home_feat5_title: "संपूर्ण कार्य जीवनचक्र",
    home_feat5_desc: "पूर्ण ऑडिट ट्रेल्स के साथ कार्य बनाएं, सौंपें, ट्रैक करें और पूर्ण करें।",
    home_feat6_title: "अनुपालन हेतु तैयार",
    home_feat6_desc: "अंतर्निहित ऑडिट लॉग, PAN/Aadhar/UAN फ़ील्ड और सुरक्षित डेटा निर्यात।",
    home_testi_badge: "टीमों द्वारा विश्वसनीय",
    home_testi_title: "हजारों उपयोगकर्ताओं का भरोसा",
    home_cta_badge: "आज ही शुरू करें — बिल्कुल मुफ़्त",
    home_cta_title1: "क्या आप अपने कार्यबल को",
    home_cta_title2: "आधुनिक बनाने के लिए तैयार हैं?",
    home_cta_desc: "50,000+ कर्मचारियों और टीमों से जुड़ें जो प्रतिदिन EmpSphere का उपयोग करते हैं।",
    home_cta_create: "निःशुल्क खाता बनाएं",
    home_cta_signin: "वर्कस्पेस में साइन इन करें",
    home_footer_login: "लॉगिन",
    home_footer_register: "पंजीकरण करें",
    home_footer_forgot: "पासवर्ड भूल गए?",
    home_footer_rights: "© 2026 EmpSphere Inc. सर्वाधिकार सुरक्षित।",
  },
  es: {
    // Navigation & Sidebar
    dashboard: "Panel",
    employees: "Empleados",
    analytics: "Analítica",
    tasks: "Tareas",
    notifications: "Notificaciones",
    workspace_hub: "Espacio de trabajo",
    profile: "Perfil",
    settings: "Ajustes",
    help: "Ayuda",
    sign_out: "Cerrar sesión",
    admin_portal: "Portal Admin",
    overview: "Visión General",
    workspace: "Espacio",
    system_mgmt: "Sistema y Gestión",
    system_admin: "Administrador del Sistema",
    emp_workspace: "Espacio del Empleado",
    active_status: "Activo",
    expand_sidebar: "Expandir barra",
    collapse_sidebar: "Colapsar barra",

    // Topbar
    search_placeholder: "Buscar...",
    search_workspace: "Buscar en espacio...",
    display_scale: "Tamaño de pantalla",
    language: "Idioma",
    text_size: "Escala de pantalla",
    size_compact: "Compacto (90%)",
    size_default: "Por Defecto (100%)",
    size_medium: "Medio (110%)",
    size_large: "Grande (125%)",
    size_xlarge: "Extra Grande (135%)",
    size_huge: "Máximo (150%)",
    reset_size: "Restablecer al 100%",
    zoom_level: "Nivel de zoom",
    accessibility_display: "Pantalla y Accesibilidad",
    notifications_title: "Notificaciones",
    mark_all_read: "Marcar leídas",
    view_all_notifications: "Ver todas",
    no_notifications: "Sin notificaciones",
    signed_in_as: "Conectado como",
    admin_role: "Administrador",
    employee_role: "Miembro del equipo",
    toggle_theme: "Cambiar tema",
    switch_light: "Modo claro",
    switch_dark: "Modo oscuro",
    decrease_size: "Disminuir tamaño",
    increase_size: "Aumentar tamaño",
    lang_set_to: "Idioma cambiado a",

    // Employees Page
    emp_directory_title: "Directorio de Empleados",
    emp_directory_subtitle: "Revisar lista de empleados, gestionar roles y permisos.",
    all_members: "Todos los miembros",
    active_staff: "Personal activo",
    blocked_staff: "Bloqueados / Suspendidos",
    export_csv: "Exportar CSV",
    search_emp_placeholder: "Buscar por nombre, email, ID, rol...",
    all_depts: "Todos los departamentos",
    sort_name_asc: "Nombre (A-Z)",
    sort_name_desc: "Nombre (Z-A)",
    sort_department: "Departamento",
    col_employee: "EMPLEADO",
    col_id_code: "CÓDIGO ID",
    col_department: "DEPARTAMENTO",
    col_role: "ROL / PUESTO",
    col_phone: "TELÉFONO",
    col_status: "ESTADO",
    col_actions: "ACCIONES",
    status_active: "ACTIVO",
    status_blocked: "BLOQUEADO",
    members_selected: "miembros seleccionados",
    member_selected: "miembro seleccionado",
    clear_selection: "Limpiar selección",
    clear: "Limpiar",
    total_personnel: "Personal total:",
    quick_options: "Opciones rápidas",
    copy_id: "Copiar ID",
    copy_email: "Copiar Email",
    view_performance: "Ver rendimiento",
    edit_credentials: "Editar credenciales",
    suspend_access: "Suspender acceso",
    unblock_account: "Desbloquear cuenta",
    delete_account: "Eliminar cuenta",
    view_label: "Ver",
    edit_label: "Editar",
    block_label: "Bloquear",
    unblock_label: "Desbloquear",
    delete_label: "Eliminar",
    cancel: "Cancelar",
    block_and_logout: "Bloquear y cerrar sesión",
    no_employees_match: "Ningún empleado coincide con la búsqueda.",
    reset_filters: "Restablecer filtros",

    // Tasks Page Header & Tabs
    tasks_workspace: "Espacio de Tareas",
    tasks_subtitle: "Gestiona y asigna tareas empresariales en equipos y empleados.",
    spaces: "Espacios",
    empsphere_workspaces: "Espacios EmpSphere",
    tab_summary: "Resumen",
    tab_list: "Lista",
    tab_board: "Tablero",
    tab_timeline: "Cronograma",
    tab_reports: "Informes",
    create_task: "Crear Tarea",
    create: "+ Crear",
    export: "Exportar",
    refresh: "Actualizar",
    search_work: "Buscar trabajo...",
    only_my_tasks: "Mis tareas",
    filter: "Filtro",
    group_by: "Agrupar",
    group_none: "Ninguno",
    group_status: "Estado",
    group_priority: "Prioridad",
    group_department: "Departamento",
    sort_by: "Ordenar",
    sort_newest: "Más reciente",
    sort_oldest: "Más antiguo",
    sort_due_date: "Fecha de vencimiento",
    sort_priority: "Prioridad",
    showing: "Mostrando",
    of: "de",
    tasks_label: "tareas",
    show_per_page: "Mostrar:",
    per_page: "por página",

    // Table Column Headers
    col_key: "CLAVE",
    col_summary: "RESUMEN",
    col_assignee: "ASIGNADO",
    col_reporter: "INFORMANTE",
    col_priority: "PRIORIDAD",
    col_resolution: "RESOLUCIÓN",
    col_assign_date: "FECHA ASIGNACIÓN",
    col_end_date: "FECHA FINALIZACIÓN",

    // Statuses & Priorities
    status_todo: "POR HACER",
    status_in_progress: "EN PROGRESO",
    status_review: "EN REVISIÓN",
    status_done: "HECHO",
    status_overdue: "Vencido",
    priority_urgent: "Urgente",
    priority_high: "Alto",
    priority_medium: "Medio",
    priority_low: "Bajo",
    resolved: "Resuelto",
    unresolved: "Sin resolver",
    unassigned: "Sin asignar",
    all_statuses: "Todos los estados",
    all_priorities: "Todas las prioridades",
    all_departments: "Todos los departamentos",
    due_today: "Vence hoy",
    due_this_week: "Vence esta semana",
    any_time: "Cualquier momento",

    // Row Actions
    delete_task: "Eliminar tarea",
    view_details: "Ver detalles",
    edit_task: "Editar tarea",
    copy_key: "Copiar clave",
    copy_link: "Copiar enlace",
    duplicate_task: "Duplicar tarea",
    quick_actions: "Acciones rápidas",
    previous: "Anterior",
    next: "Siguiente",
    page: "Página",

    // Analytics Page
    analytics_title: "Rendimiento y Analítica",
    analytics_admin_sub: "Rendimiento empresarial, crecimiento y analítica de tareas.",
    analytics_user_sub: "Desglose detallado de su velocidad de tareas y productividad.",
    total_ent_users: "Total de Usuarios Empresariales",
    my_assigned_tasks: "Mis Tareas Asignadas",
    verified_members: "Miembros Verificados",
    total_workload_items: "Elementos de Carga Total",
    prod_velocity: "Velocidad de Productividad",
    task_comp_rate: "Tasa de Finalización de Tareas",
    completed_milestones: "Hitos Entregados",
    completed_tasks_title: "Tareas Completadas",
    in_prog_review: "En Progreso y Revisión",
    active_pipeline: "Canal Activo Actual",
    org_growth_velocity: "Crecimiento Organizacional y Velocidad",
    monthly_delivery_velocity: "Velocidad Mensual de Entrega",
    task_status_breakdown: "Desglose de Estado de Tareas",
    weekly_task_cadence: "Cadencia Semanal de Tareas (Lun – Dom)",
    workload_priority: "Carga de Trabajo por Prioridad",
    dept_distribution_title: "Distribución por Departamento",
    workforce_demographics: "Demografía de Edad Laboral",

    // Notifications Page
    notif_hub_title: "Centro de Notificaciones y Actividad",
    notif_hub_sub: "Flujo de actividad de empleados en tiempo real y alertas.",
    activity_center: "Centro de Actividad",
    all_caught_up: "Todo al día",
    unread_and_new: "No leídas y Nuevas",
    all_activity_logs: "Todos los Registros de Actividad",
    workspace_messages: "Mensajes del Espacio",
    search_notif_placeholder: "Buscar notificaciones, tareas o miembros...",
    no_notifs_found: "No se encontraron notificaciones",

    // Dashboard
    good_day: "Buen día",
    admin_overview: "Resumen de Administrador",
    workspace_overview: "Resumen del Espacio",
    view_my_tasks: "Ver Mis Tareas",
    manage_tasks: "Gestionar Tareas",
    total_tasks: "TOTAL TAREAS",
    pending: "PENDIENTES",
    in_progress: "EN PROGRESO",
    completed: "COMPLETADAS",
    overdue: "VENCIDAS",
    completion_rate: "TASA DE FINALIZACIÓN",
    task_distribution: "Distribución de Tareas",
    realtime_breakdown: "Desglose del estado en tiempo real",
    weekly_activity: "Actividad Semanal",
    weekly_subtitle: "Creado vs Completado esta semana",
    live_badge: "En vivo",
    created_label: "Creado",
    completed_label: "Completado",
    dept_workload: "Carga de Trabajo por Departamento",
    dept_subtitle: "Velocidad de ejecución y desglose entre equipos",
    team_directory: "Directorio de equipos →",
    total_label: "Total",
    active_label: "Activo",
    pending_backlog: "trabajo pendiente",
    view_tasks_arrow: "Ver tareas →",
    dept_operations: "Operaciones",
    dept_engineering: "Ingeniería",
    dept_sales: "Ventas y Negocios",
    dept_design: "Diseño",
    dept_hr: "Recursos Humanos",
    dept_leadership: "Liderazgo Ejecutivo",
    recent_activity: "Actividad Reciente",
    recent_subtitle: "Actualizaciones en tiempo real y estados",
    view_all_tasks: "Ver todas las tareas",
    no_recent_activities: "No hay actividades recientes",
    workspace_calendar: "Calendario",
    interactive: "Interactivo",
    day_schedule: "Horario del Día",
    no_tasks_date: "No hay tareas programadas en esta fecha.",
    high_priority_attention: "Atención de Alta Prioridad",
    no_due_date: "Sin fecha de vencimiento",
    no_urgent_tasks: "No hay tareas urgentes.",
    days_mo: "Lu",
    days_tu: "Ma",
    days_we: "Mi",
    days_th: "Ju",
    days_fr: "Vi",
    days_sa: "Sá",
    days_su: "Do",
    task_singular: "tarea",
    tasks_plural: "tareas",
    quick_shortcuts: "Accesos Rápidos y Estado",
    system_operational: "Todos los sistemas operativos",
    system_uptime: "99.98% SLA de Actividad",
    sprint_goals: "Velocidad y Metas de Sprint",
    monthly_milestone: "Objetivo Mensual",
    top_contributors: "Principales Contribuidores",
    velocity_on_track: "En tiempo",
    tasks_completed_count: "tareas completadas",
    export_report: "Exportar Reporte de Auditoría",
    invite_member: "Invitar Miembro del Equipo",

    // Auth Pages (Login, Register, Forgot, Reset, Admin)
    auth_welcome_back: "Bienvenido de nuevo",
    auth_login_subtitle: "Inicia sesión en tu espacio de trabajo y continúa donde lo dejaste.",
    auth_work_email: "Correo Corporativo",
    auth_password: "Contraseña",
    auth_remember_me: "Recordarme",
    auth_forgot_password: "¿Olvidaste tu contraseña?",
    auth_login_btn: "Iniciar Sesión",
    auth_logging_in: "Iniciando sesión...",
    auth_new_to_empsphere: "¿Nuevo en EmpSphere?",
    auth_create_account: "Crear una cuenta",
    auth_create_title: "Crea tu cuenta",
    auth_create_subtitle: "Comienza con el espacio de trabajo de gestión de tareas de tu equipo.",
    auth_required_hint: "Los campos marcados con un asterisco (*) son obligatorios.",
    auth_first_name: "Nombre",
    auth_last_name: "Apellido",
    auth_phone_number: "Número de Teléfono",
    auth_department: "Departamento",
    auth_select_department: "Seleccionar departamento",
    auth_role: "Tu Rol",
    auth_select_role: "Seleccionar rol",
    auth_confirm_password: "Confirmar Contraseña",
    auth_emp_id: "ID de Empleado",
    auth_emp_id_hint: "Asignado automáticamente. El administrador puede editarlo más tarde.",
    auth_dob: "Fecha de Nacimiento",
    auth_dob_hint: "Debe tener al menos 18 años",
    auth_agree_terms: "Acepto los",
    auth_terms: "Términos de Servicio",
    auth_and: "y la",
    auth_privacy: "Política de Privacidad",
    auth_create_btn: "Crear Cuenta",
    auth_creating_account: "Creando Cuenta...",
    auth_clear_draft: "Borrar Borrador",
    auth_already_have_account: "¿Ya tienes una cuenta?",
    auth_sign_in_link: "Iniciar Sesión",
    auth_forgot_title: "¿Olvidaste tu contraseña?",
    auth_forgot_subtitle: "Ingresa el correo vinculado a tu cuenta y te enviaremos un enlace de restablecimiento.",
    auth_send_reset_btn: "Enviar enlace",
    auth_sending_link: "Enviando enlace...",
    auth_back_to_sign_in: "Volver a Iniciar Sesión",
    auth_reset_title: "Establecer nueva contraseña",
    auth_reset_subtitle: "Elige una contraseña segura con letras, números y símbolos.",
    auth_reset_btn: "Restablecer contraseña",
    auth_resetting_password: "Actualizando contraseña...",
    auth_admin_portal: "Portal Admin",
    auth_admin_title: "Portal de Administrador",
    auth_admin_subtitle: "Inicia sesión con tus credenciales de administrador",
    auth_admin_email: "Correo de Administrador",
    auth_enter_portal: "Entrar al Portal",
    auth_employee_login: "Login de Empleado",
    auth_sec_feature1: "Seguridad de nivel empresarial",
    auth_sec_feature2: "Colaboración fluida de equipo",
    auth_sec_feature3: "Rendimiento ultra rápido",
    auth_hero_heading: "Gestiona tareas con",
    auth_hero_highlight: "absoluta claridad.",
    auth_hero_sub: "Únete a miles de equipos modernos que usan EmpSphere para alinear su organización.",

    // Home Page (Spanish)
    home_nav_features: "Características",
    home_nav_security: "Seguridad",
    home_nav_analytics: "Analítica",
    home_nav_signin: "Iniciar sesión",
    home_hero_badge: "Plataforma de Gestión Laboral Empresarial",
    home_hero_title1: "El sistema operativo para tu",
    home_hero_title2: "fuerza laboral moderna",
    home_hero_desc: "EmpSphere unifica gestión de tareas, análisis de equipo, nómina y accesos por rol en un espacio corporativo elegante.",
    home_hero_cta: "Entrar al espacio de trabajo",
    home_stat_uptime: "Disponibilidad SLA",
    home_stat_users: "Usuarios Activos",
    home_stat_tasks: "Tareas Gestionadas",
    home_stat_countries: "Países",
    home_portals_badge: "Portales de Acceso",
    home_portals_title: "Elige tu espacio de trabajo",
    home_portals_desc: "Dos portales dedicados. Una plataforma unificada. Acceso seguro y adaptado a roles.",
    home_emp_portal_badge: "Portal de Empleado",
    home_emp_portal_title: "Acceso para Empleados",
    home_emp_portal_desc: "Accede a tus tareas, recibos de nómina, gestiona tu perfil y colabora con tu equipo desde un solo panel.",
    home_emp_feat_1: "Panel personal de tareas",
    home_emp_feat_2: "Resumen salarial y nómina",
    home_emp_feat_3: "Centro de colaboración",
    home_emp_feat_4: "Gestión de perfil y documentos",
    home_emp_btn: "Iniciar sesión como Empleado",
    home_emp_new_here: "¿Eres nuevo?",
    home_emp_create_acc: "Crear cuenta",
    home_admin_portal_badge: "Acceso Restringido",
    home_admin_portal_title: "Portal de Administrador",
    home_admin_portal_desc: "Acceso privilegiado para Super Admins y Administradores para gestionar la organización.",
    home_admin_feat_1: "Super Admin — Control total",
    home_admin_feat_2: "System Admin — Seguridad y auditoría",
    home_admin_feat_3: "Admin — Gestión de personal y tareas",
    home_admin_feat_4: "Auditorías, analítica y reportes",
    home_admin_btn: "Entrar al espacio de trabajo",
    home_admin_subtext: "Inicio de sesión empresarial unificado",
    home_analytics_badge: "Inteligencia y Perspectivas Laborales",
    home_analytics_title: "Analítica en tiempo real para líderes",
    home_analytics_desc: "Visibilidad profunda de velocidad de equipo, resolución de tareas y productividad laboral.",
    home_analytics_stat1_val: "94.2%",
    home_analytics_stat1_lbl: "Velocidad de Tareas",
    home_analytics_stat1_sub: "+8.4% más rápido que el mes anterior",
    home_analytics_stat2_val: "1.8 h",
    home_analytics_stat2_lbl: "Tiempo Medio de Resolución",
    home_analytics_stat2_sub: "32% entrega más ágil",
    home_analytics_stat3_val: "98.6%",
    home_analytics_stat3_lbl: "Tasa de Actividad Laboral",
    home_analytics_stat3_sub: "Alto índice de compromiso",
    home_analytics_stat4_val: "99.4%",
    home_analytics_stat4_lbl: "Cumplimiento de SLA",
    home_analytics_stat4_sub: "Cero infracciones",
    home_analytics_card_title: "Matriz de Productividad en Vivo",
    home_analytics_card_sub: "Rendimiento organizacional en tiempo real por departamentos",
    home_dept_eng: "Ingeniería",
    home_dept_prod: "Diseño de Producto",
    home_dept_ops: "Operaciones",
    home_dept_hr: "Recursos Humanos (RRHH)",
    home_analytics_live_feed: "Pulso de Rendimiento en Vivo",
    home_analytics_pulse1: "Velocidad del Sprint 14 completada antes de plazo",
    home_analytics_pulse2: "99.8% entrega a tiempo en tareas activas",
    home_analytics_pulse3: "Cero alertas de seguridad en auditoría mensual",
    home_features_badge: "Características de la Plataforma",
    home_features_title: "Todo lo que tu equipo necesita",
    home_features_desc: "Construido para escalar, diseñado para la claridad.",
    home_feat1_title: "Seguridad Empresarial",
    home_feat1_desc: "Autenticación JWT militar, RBAC, verificación OTP y limitación de peticiones.",
    home_feat2_title: "Analítica en Tiempo Real",
    home_feat2_desc: "Gráficos de 6 meses, puntuaciones de productividad y métricas en vivo.",
    home_feat3_title: "Gestión de Equipos",
    home_feat3_desc: "Portales basados en roles para Super Admin, Admin y Empleados.",
    home_feat4_title: "Rendimiento Ultrarrápido",
    home_feat4_desc: "Actualizaciones de interfaz optimistas y sincronización en segundo plano.",
    home_feat5_title: "Ciclo Completo de Tareas",
    home_feat5_desc: "Crea, asigna, rastrea y audita tareas de principio a fin.",
    home_feat6_title: "Listo para Cumplimiento",
    home_feat6_desc: "Registros de auditoría integrados y exportación segura de datos.",
    home_testi_badge: "Confiado por Equipos",
    home_testi_title: "La elección de miles",
    home_cta_badge: "Comienza Hoy — Gratis",
    home_cta_title1: "¿Listo para transformar",
    home_cta_title2: "tu equipo de trabajo?",
    home_cta_desc: "Únete a más de 50,000 empleados y equipos que utilizan EmpSphere a diario.",
    home_cta_create: "Crear Cuenta Gratuita",
    home_cta_signin: "Entrar al Espacio de Trabajo",
    home_footer_login: "Iniciar Sesión",
    home_footer_register: "Registrarse",
    home_footer_forgot: "¿Olvidaste tu contraseña?",
    home_footer_rights: "© 2026 EmpSphere Inc. Todos los derechos reservados.",
  },
  fr: {
    // Navigation & Sidebar
    dashboard: "Tableau de bord",
    employees: "Employés",
    analytics: "Analytique",
    tasks: "Tâches",
    notifications: "Notifications",
    workspace_hub: "Espace de travail",
    profile: "Profil",
    settings: "Paramètres",
    help: "Aide",
    sign_out: "Se déconnecter",
    admin_portal: "Portail Admin",
    overview: "Aperçu",
    workspace: "Espace",
    system_mgmt: "Système & Gestion",
    system_admin: "Administrateur Système",
    emp_workspace: "Espace Employé",
    active_status: "Actif",
    expand_sidebar: "Agrandir le menu",
    collapse_sidebar: "Réduire le menu",

    // Topbar
    search_placeholder: "Rechercher...",
    search_workspace: "Rechercher dans l'espace...",
    display_scale: "Taille d'affichage",
    language: "Langue",
    text_size: "Échelle d'affichage",
    size_compact: "Compact (90%)",
    size_default: "Par défaut (100%)",
    size_medium: "Moyen (110%)",
    size_large: "Grand (125%)",
    size_xlarge: "Très Grand (135%)",
    size_huge: "Maximum (150%)",
    reset_size: "Réinitialiser à 100%",
    zoom_level: "Niveau de zoom",
    accessibility_display: "Affichage et Accessibilité",
    notifications_title: "Notifications",
    mark_all_read: "Tout marquer lu",
    view_all_notifications: "Voir toutes les notifications",
    no_notifications: "Aucune notification",
    signed_in_as: "Connecté en tant que",
    admin_role: "Administrateur",
    employee_role: "Membre de l'équipe",
    toggle_theme: "Changer de thème",
    switch_light: "Mode clair",
    switch_dark: "Mode sombre",
    decrease_size: "Diminuer la taille",
    increase_size: "Augmenter la taille",
    lang_set_to: "Langue définie sur",

    // Employees Page
    emp_directory_title: "Annuaire des Employés",
    emp_directory_subtitle: "Consultez la liste des employés, gérez les rôles et permissions.",
    all_members: "Tous les membres",
    active_staff: "Personnel actif",
    blocked_staff: "Bloqués / Suspendus",
    export_csv: "Exporter CSV",
    search_emp_placeholder: "Rechercher par nom, email, ID, rôle...",
    all_depts: "Tous les départements",
    sort_name_asc: "Nom (A-Z)",
    sort_name_desc: "Nom (Z-A)",
    sort_department: "Département",
    col_employee: "EMPLOYÉ",
    col_id_code: "CODE ID",
    col_department: "DÉPARTEMENT",
    col_role: "RÔLE / POSTE",
    col_phone: "TÉLÉPHONE",
    col_status: "STATUT",
    col_actions: "ACTIONS",
    status_active: "ACTIF",
    status_blocked: "BLOQUÉ",
    members_selected: "membres sélectionnés",
    member_selected: "membre sélectionné",
    clear_selection: "Effacer la sélection",
    clear: "Effacer",
    total_personnel: "Personnel total :",
    quick_options: "Options rapides",
    copy_id: "Copier l'ID",
    copy_email: "Copier l'email",
    view_performance: "Voir les performances",
    edit_credentials: "Modifier les identifiants",
    suspend_access: "Suspendre l'accès",
    unblock_account: "Débloquer le compte",
    delete_account: "Supprimer le compte",
    view_label: "Voir",
    edit_label: "Modifier",
    block_label: "Bloquer",
    unblock_label: "Débloquer",
    delete_label: "Supprimer",
    cancel: "Annuler",
    block_and_logout: "Bloquer et déconnecter",
    no_employees_match: "Aucun employé ne correspond à votre recherche.",
    reset_filters: "Réinitialiser les filtres",

    // Tasks Page Header & Tabs
    tasks_workspace: "Espace des Tâches",
    tasks_subtitle: "Gérez et assignez les tâches de l'entreprise entre équipes.",
    spaces: "Espaces",
    empsphere_workspaces: "Espaces EmpSphere",
    tab_summary: "Résumé",
    tab_list: "Liste",
    tab_board: "Tableau",
    tab_timeline: "Chronologie",
    tab_reports: "Rapports",
    create_task: "Créer une tâche",
    create: "+ Créer",
    export: "Exporter",
    refresh: "Actualiser",
    search_work: "Rechercher une tâche...",
    only_my_tasks: "Mes tâches",
    filter: "Filtrer",
    group_by: "Grouper par",
    group_none: "Aucun",
    group_status: "Statut",
    group_priority: "Priorité",
    group_department: "Département",
    sort_by: "Trier par",
    sort_newest: "Plus récent",
    sort_oldest: "Plus ancien",
    sort_due_date: "Date d'échéance",
    sort_priority: "Priorité",
    showing: "Affichage de",
    of: "sur",
    tasks_label: "tâches",
    show_per_page: "Afficher :",
    per_page: "par page",

    // Table Column Headers
    col_key: "CLÉ",
    col_summary: "RÉSUMÉ",
    col_assignee: "ASSIGNÉ",
    col_reporter: "RAPPORTEUR",
    col_priority: "PRIORITÉ",
    col_resolution: "RÉSOLUTION",
    col_assign_date: "DATE D'ATTRIBUTION",
    col_end_date: "DATE D'ÉCHÉANCE",

    // Statuses & Priorities
    status_todo: "À FAIRE",
    status_in_progress: "EN COURS",
    status_review: "EN REVUE",
    status_done: "TERMINÉ",
    status_overdue: "En retard",
    priority_urgent: "Urgent",
    priority_high: "Élevé",
    priority_medium: "Moyen",
    priority_low: "Bas",
    resolved: "Résolu",
    unresolved: "Non résolu",
    unassigned: "Non assigné",
    all_statuses: "Tous les statuts",
    all_priorities: "Toutes les priorités",
    all_departments: "Tous les départements",
    due_today: "Dû aujourd'hui",
    due_this_week: "Dû cette semaine",
    any_time: "Tout moment",

    // Row Actions
    delete_task: "Supprimer",
    view_details: "Voir détails",
    edit_task: "Modifier",
    copy_key: "Copier la clé",
    copy_link: "Copier le lien",
    duplicate_task: "Dupliquer",
    quick_actions: "Actions rapides",
    previous: "Précédent",
    next: "Suivant",
    page: "Page",

    // Analytics Page
    analytics_title: "Performance & Analytique",
    analytics_admin_sub: "Performances globales de l'entreprise et analytique.",
    analytics_user_sub: "Détails de votre vélocité de tâches et productivité.",
    total_ent_users: "Total Utilisateurs Entreprise",
    my_assigned_tasks: "Mes Tâches Assignées",
    verified_members: "Membres Vérifiés",
    total_workload_items: "Total des Éléments de Travail",
    prod_velocity: "Vélocité de Productivité",
    task_comp_rate: "Taux d'Achèvement des Tâches",
    completed_milestones: "Jalons Livrés",
    completed_tasks_title: "Tâches Terminées",
    in_prog_review: "En Cours et En Revue",
    active_pipeline: "Pipeline Actif Actuel",
    org_growth_velocity: "Croissance de l'Organisation & Vélocité",
    monthly_delivery_velocity: "Vélocité Mensuelle de Livraison",
    task_status_breakdown: "Répartition des Statuts de Tâches",
    weekly_task_cadence: "Cadence Hebdomadaire des Tâches (Lun – Dim)",
    workload_priority: "Charge de Travail par Priorité",
    dept_distribution_title: "Répartition par Département",
    workforce_demographics: "Démographie d'Âge du Personnel",

    // Notifications Page
    notif_hub_title: "Centre de Notifications & d'Activité",
    notif_hub_sub: "Flux d'activité en temps réel et alertes de l'espace.",
    activity_center: "Centre d'Activité",
    all_caught_up: "Tout est à jour",
    unread_and_new: "Non lues & Nouvelles",
    all_activity_logs: "Tous les Journaux d'Activité",
    workspace_messages: "Messages de l'Espace",
    search_notif_placeholder: "Rechercher notifications, tâches ou membres...",
    no_notifs_found: "Aucune notification trouvée",

    // Dashboard
    good_day: "Bonjour",
    admin_overview: "Aperçu Administrateur",
    workspace_overview: "Aperçu de l'Espace",
    view_my_tasks: "Voir Mes Tâches",
    manage_tasks: "Gérer les Tâches",
    total_tasks: "TOTAL TÂCHES",
    pending: "EN ATTENTE",
    in_progress: "EN COURS",
    completed: "TERMINÉ",
    overdue: "EN RETARD",
    completion_rate: "TAUX D'ACHÈVEMENT",
    task_distribution: "Distribution des Tâches",
    realtime_breakdown: "Répartition en temps réel",
    weekly_activity: "Activité Hebdomadaire",
    weekly_subtitle: "Créé vs Terminé cette semaine",
    live_badge: "En direct",
    created_label: "Créé",
    completed_label: "Terminé",
    dept_workload: "Charge de Travail par Département",
    dept_subtitle: "Vélocité d'exécution et répartition des équipes",
    team_directory: "Annuaire des équipes →",
    total_label: "Total",
    active_label: "Actif",
    pending_backlog: "arriéré en attente",
    view_tasks_arrow: "Voir les tâches →",
    dept_operations: "Opérations",
    dept_engineering: "Ingénierie",
    dept_sales: "Ventes et Affaires",
    dept_design: "Design",
    dept_hr: "Ressources Humaines",
    dept_leadership: "Direction Exécutive",
    recent_activity: "Activité Récente",
    recent_subtitle: "Mises à jour en temps réel",
    view_all_tasks: "Voir toutes les tâches",
    no_recent_activities: "Aucune activité récente",
    workspace_calendar: "Calendrier",
    interactive: "Interactif",
    day_schedule: "Emploi du Temps",
    no_tasks_date: "Aucune tâche planifiée à cette date.",
    high_priority_attention: "Attention Haute Priorité",
    no_due_date: "Pas de date d'échéance",
    no_urgent_tasks: "Aucune tâche urgente.",
    days_mo: "Lu",
    days_tu: "Ma",
    days_we: "Me",
    days_th: "Je",
    days_fr: "Ve",
    days_sa: "Sa",
    days_su: "Di",
    task_singular: "tâche",
    tasks_plural: "tâches",
    quick_shortcuts: "Raccourcis et État du Système",
    system_operational: "Tous les systèmes opérationnels",
    system_uptime: "SLA de disponibilité 99,98%",
    sprint_goals: "Vélocité et Objectifs du Sprint",
    monthly_milestone: "Objectif Mensuel",
    top_contributors: "Principaux Contributeurs",
    velocity_on_track: "Dans les temps",
    tasks_completed_count: "tâches terminées",
    export_report: "Exporter le Rapport d'Audit",
    invite_member: "Inviter un Membre d'Équipe",

    // Auth Pages (Login, Register, Forgot, Reset, Admin)
    auth_welcome_back: "Bon retour",
    auth_login_subtitle: "Connectez-vous à votre espace de travail et reprenez là où vous en étiez.",
    auth_work_email: "E-mail Professionnel",
    auth_password: "Mot de passe",
    auth_remember_me: "Se souvenir de moi",
    auth_forgot_password: "Mot de passe oublié ?",
    auth_login_btn: "Se connecter",
    auth_logging_in: "Connexion en cours...",
    auth_new_to_empsphere: "Nouveau sur EmpSphere ?",
    auth_create_account: "Créer un compte",
    auth_create_title: "Créez votre compte",
    auth_create_subtitle: "Commencez avec l'espace de gestion des tâches de votre équipe.",
    auth_required_hint: "Les champs marqués d'un astérisque (*) sont obligatoires.",
    auth_first_name: "Prénom",
    auth_last_name: "Nom",
    auth_phone_number: "Numéro de Téléphone",
    auth_department: "Département",
    auth_select_department: "Sélectionner un département",
    auth_role: "Votre Rôle",
    auth_select_role: "Sélectionner un rôle",
    auth_confirm_password: "Confirmer le Mot de passe",
    auth_emp_id: "ID Employé",
    auth_emp_id_hint: "Assigné automatiquement. Modifiable ultérieurement par un admin.",
    auth_dob: "Date de Naissance",
    auth_dob_hint: "Doit avoir au moins 18 ans",
    auth_agree_terms: "J'accepte les",
    auth_terms: "Conditions d'Utilisation",
    auth_and: "et la",
    auth_privacy: "Politique de Confidentialité",
    auth_create_btn: "Créer un Compte",
    auth_creating_account: "Création du compte...",
    auth_clear_draft: "Effacer le brouillon",
    auth_already_have_account: "Vous avez déjà un compte ?",
    auth_sign_in_link: "Se connecter",
    auth_forgot_title: "Mot de passe oublié ?",
    auth_forgot_subtitle: "Entrez l'e-mail lié à votre compte et nous vous enverrons un lien.",
    auth_send_reset_btn: "Envoyer le lien",
    auth_sending_link: "Envoi en cours...",
    auth_back_to_sign_in: "Retour à la connexion",
    auth_reset_title: "Définir un nouveau mot de passe",
    auth_reset_subtitle: "Choisissez un mot de passe fort avec lettres, chiffres et symboles.",
    auth_reset_btn: "Réinitialiser le mot de passe",
    auth_resetting_password: "Mise à jour du mot de passe...",
    auth_admin_portal: "Portail Admin",
    auth_admin_title: "Portail Administrateur",
    auth_admin_subtitle: "Connectez-vous avec vos identifiants administrateur",
    auth_admin_email: "E-mail Administrateur",
    auth_enter_portal: "Entrer dans le Portail",
    auth_employee_login: "Connexion Employé",
    auth_sec_feature1: "Sécurité de niveau entreprise",
    auth_sec_feature2: "Collaboration d'équipe fluide",
    auth_sec_feature3: "Performances ultra rapides",
    auth_hero_heading: "Gérez vos tâches avec",
    auth_hero_highlight: "une clarté absolue.",
    auth_hero_sub: "Rejoignez des milliers d'équipes modernes qui utilisent EmpSphere.",

    // Home Page (French)
    home_nav_features: "Fonctionnalités",
    home_nav_security: "Sécurité",
    home_nav_analytics: "Analytique",
    home_nav_signin: "Connexion",
    home_hero_badge: "Plateforme de Gestion de la Main-d'œuvre Entreprise",
    home_hero_title1: "Le système d'exploitation pour votre",
    home_hero_title2: "équipe moderne",
    home_hero_desc: "EmpSphere rassemble la gestion des tâches, les analyses d'équipe, les fiches de paie et l'accès basé sur les rôles.",
    home_hero_cta: "Accéder à l'espace de travail",
    home_stat_uptime: "Disponibilité SLA",
    home_stat_users: "Utilisateurs Actifs",
    home_stat_tasks: "Tâches Gérées",
    home_stat_countries: "Pays",
    home_portals_badge: "Portails d'Accès",
    home_portals_title: "Choisissez votre espace de travail",
    home_portals_desc: "Deux portails dédiés. Une plateforme unifiée. Accès sécurisé et adapté à chaque rôle.",
    home_emp_portal_badge: "Portail Employé",
    home_emp_portal_title: "Connexion Employé",
    home_emp_portal_desc: "Accédez à vos tâches, consultez vos bulletins de salaire et collaborez avec votre équipe.",
    home_emp_feat_1: "Tableau de bord personnel",
    home_emp_feat_2: "Aperçu salarial & paie",
    home_emp_feat_3: "Hub de collaboration d'équipe",
    home_emp_feat_4: "Gestion de profil et documents",
    home_emp_btn: "Se connecter comme Employé",
    home_emp_new_here: "Nouveau ici ?",
    home_emp_create_acc: "Créer un compte",
    home_admin_portal_badge: "Accès Restreint",
    home_admin_portal_title: "Portail Administrateur",
    home_admin_portal_desc: "Accès privilégié pour les Super Admins et Administrateurs pour gérer l'organisation.",
    home_admin_feat_1: "Super Admin — Contrôle total",
    home_admin_feat_2: "System Admin — Sécurité & audit",
    home_admin_feat_3: "Admin — Gestion utilisateurs et tâches",
    home_admin_feat_4: "Journaux d'audit et rapports",
    home_admin_btn: "Accéder à l'espace de travail",
    home_admin_subtext: "Connexion d'entreprise unifiée",
    home_analytics_badge: "Intelligence & Perspectives d'Équipe",
    home_analytics_title: "Analytique en temps réel pour les dirigeants",
    home_analytics_desc: "Visibilité approfondie sur la vélocité, l'efficacité des tâches et la productivité globale.",
    home_analytics_stat1_val: "94.2%",
    home_analytics_stat1_lbl: "Vélocité des Tâches",
    home_analytics_stat1_sub: "+8.4% plus rapide que le mois dernier",
    home_analytics_stat2_val: "1.8 h",
    home_analytics_stat2_lbl: "Délai Moyen de Résolution",
    home_analytics_stat2_sub: "32% plus rapide",
    home_analytics_stat3_val: "98.6%",
    home_analytics_stat3_lbl: "Taux d'Activité d'Équipe",
    home_analytics_stat3_sub: "Indice d'engagement élevé",
    home_analytics_stat4_val: "99.4%",
    home_analytics_stat4_lbl: "Conformité SLA",
    home_analytics_stat4_sub: "Zéro violation",
    home_analytics_card_title: "Matrice de Productivité en Direct",
    home_analytics_card_sub: "Performance organisationnelle en temps réel par département",
    home_dept_eng: "Ingénierie",
    home_dept_prod: "Conception Produit",
    home_dept_ops: "Opérations",
    home_dept_hr: "Ressources Humaines (RH)",
    home_analytics_live_feed: "Pouls de Performance en Direct",
    home_analytics_pulse1: "Vélocité Sprint 14 terminée en avance",
    home_analytics_pulse2: "99.8% de livraisons dans les délais",
    home_analytics_pulse3: "Zéro risque de sécurité lors de l'audit",
    home_features_badge: "Fonctionnalités de la Plateforme",
    home_features_title: "Tout ce dont votre équipe a besoin",
    home_features_desc: "Conçu pour la croissance, pensé pour la clarté.",
    home_feat1_title: "Sécurité Entreprise",
    home_feat1_desc: "Authentification JWT robuste, RBAC, vérification OTP et limitation de débit.",
    home_feat2_title: "Analytique en Temps Réel",
    home_feat2_desc: "Graphiques d'évolution, scores de productivité et indicateurs en direct.",
    home_feat3_title: "Gestion d'Équipe",
    home_feat3_desc: "Portails dédiés pour Super Admin, Admin et Employés.",
    home_feat4_title: "Performances Éclair",
    home_feat4_desc: "Mises à jour optimistes et synchronisation instantanée.",
    home_feat5_title: "Cycle de Vie Complet des Tâches",
    home_feat5_desc: "Créez, assignez, suivez et archivez vos tâches avec audit complet.",
    home_feat6_title: "Conforme aux Normes",
    home_feat6_desc: "Journaux d'audit natifs et export sécurisé des données.",
    home_testi_badge: "Approuvé par les Équipes",
    home_testi_title: "Adopté par des milliers d'utilisateurs",
    home_cta_badge: "Commencez Aujourd'hui — Gratuit",
    home_cta_title1: "Prêt à transformer",
    home_cta_title2: "votre équipe ?",
    home_cta_desc: "Rejoignez plus de 50 000 collaborateurs qui utilisent EmpSphere chaque jour.",
    home_cta_create: "Créer un Compte Gratuit",
    home_cta_signin: "Accéder à l'Espace de Travail",
    home_footer_login: "Connexion",
    home_footer_register: "S'inscrire",
    home_footer_forgot: "Mot de passe oublié ?",
    home_footer_rights: "© 2026 EmpSphere Inc. Tous droits réservés.",
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  currentLanguageOption: LanguageOption;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<LanguageCode>("en");

  useEffect(() => {
    const savedLang = (localStorage.getItem("app_language") as LanguageCode) || "en";
    if (["en", "hi", "es", "fr"].includes(savedLang)) {
      setLanguageState(savedLang);
      document.documentElement.lang = savedLang;
    }
  }, []);

  const setLanguage = (newLang: LanguageCode) => {
    setLanguageState(newLang);
    localStorage.setItem("app_language", newLang);
    document.documentElement.lang = newLang;
    window.dispatchEvent(new Event("language-change"));
  };

  const currentLanguageOption =
    LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];

  const t = (key: string, fallback?: string): string => {
    return TRANSLATIONS[language]?.[key] || fallback || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        currentLanguageOption,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    // Return safe fallback if outside provider
    return {
      language: "en" as LanguageCode,
      setLanguage: () => {},
      currentLanguageOption: LANGUAGES[0],
      t: (key: string, fallback?: string) => fallback || key,
    };
  }
  return context;
};
